development:
  adapter: postgresql
  encoding: unicode
  database: emotethis_ror_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: emotethis_ror_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: emotethis_ror_production
  pool: 5
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: emotethis_ror_staging
  pool: 5
  username: postgres
  password:

demo:
  adapter: postgresql
  encoding: unicode
  database: emotethis_ror_demo
  pool: 5
  username: postgres
  password: