defaults: &defaults
  host: flame.mongohq.com
  username: rubyriders
  password: 134711
  autocreate_indexes: true
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: false
  reconnect_time: 3

development:
  <<: *defaults
  database: emote_dev
  port: 27041

test:
  <<: *defaults
  database: emote_test

production:
  <<: *defaults
  database: emote
  port: 27049
